[build-system]
requires = ["hatchling==1.27.0"]
build-backend = "hatchling.build"

[project]
name = "spectralab-backend"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
  "fastapi==0.118.0",
  "pydantic-settings==2.11.0",
  "python-multipart==0.0.20",
  "spectralab-ml",
  "uvicorn[standard]==0.37.0",
]

[tool.uv.sources]
spectralab-ml = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["app"]
