/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/elements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Elements */
        get: operations["elements_api_v1_elements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spectra/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_api_v1_spectra_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spectra/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_v1_spectra_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spectra/{spectrum_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Spectrum */
        get: operations["get_spectrum_api_v1_spectra__spectrum_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict */
        post: operations["predict_api_v1_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Experiments */
        get: operations["list_experiments_api_v1_experiments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment */
        get: operations["get_experiment_api_v1_experiments__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_api_v1_spectra_upload_post */
        Body_upload_api_v1_spectra_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Units */
            units: string;
            /** Wavelength Medium */
            wavelength_medium: string;
        };
        /** ElementScore */
        ElementScore: {
            /** Element */
            element: string;
            /** Value */
            value: number;
        };
        /** ElementsInfo */
        ElementsInfo: {
            /** Elements */
            elements: string[];
            /** Ion Stage */
            ion_stage: number;
            /** Reference */
            reference: {
                [key: string]: unknown;
            };
            /** Line Counts */
            line_counts: {
                [key: string]: number;
            };
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: unknown | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** ExperimentCondition */
        ExperimentCondition: {
            /** Model Id */
            model_id: string;
            /** Factor */
            factor: string;
            /** Value */
            value: number | null;
            /** Requested Value */
            requested_value: number | string | null;
            /** Test Base Sample Ids */
            test_base_sample_ids: string[];
            metrics: components["schemas"]["ExperimentMetrics"];
        };
        /** ExperimentDetail */
        ExperimentDetail: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
            /** Reference Source */
            reference_source: string;
            /** Protocol */
            protocol: string;
            /** Demo */
            demo: boolean;
            /** Configuration */
            configuration: {
                [key: string]: unknown;
            };
            /** Seed */
            seed: number;
            /** Runs */
            runs: components["schemas"]["ExperimentCondition"][];
            /** Limitations */
            limitations: string;
        } & {
            [key: string]: unknown;
        };
        /** ExperimentMetrics */
        ExperimentMetrics: {
            /** Micro F1 */
            micro_f1: number;
            /** Macro F1 */
            macro_f1: number;
            /** Exact Match Accuracy */
            exact_match_accuracy: number;
            /** Hamming Loss */
            hamming_loss: number;
            /** Per Element */
            per_element: {
                [key: string]: components["schemas"]["PerElementMetrics"];
            };
            single: components["schemas"]["SubsetMetrics"];
            mixture: components["schemas"]["SubsetMetrics"];
            /** Undefined Metric Policy */
            undefined_metric_policy: string;
            /** Inference Ms Per Spectrum */
            inference_ms_per_spectrum?: number | null;
            /** Timing Method */
            timing_method?: string | null;
        };
        /** ExperimentSummary */
        ExperimentSummary: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
            /** Reference Source */
            reference_source: string;
            /** Protocol */
            protocol: string;
            /** Demo */
            demo: boolean;
        };
        /** GenerateSpectrumRequest */
        GenerateSpectrumRequest: {
            /** Elements */
            elements: string[];
            /** Component Weights */
            component_weights: number[];
            /**
             * Instrumental Fwhm Nm
             * @default 0.5
             */
            instrumental_fwhm_nm: number;
            /**
             * Sampling Step Nm
             * @default 0.05
             */
            sampling_step_nm: number;
            /**
             * Snr Db
             * @default 20
             */
            snr_db: number | null;
            /**
             * Background Level
             * @default 0
             */
            background_level: number;
            /**
             * Background Slope
             * @default 0
             */
            background_slope: number;
            /**
             * Calibration Shift Nm
             * @default 0
             */
            calibration_shift_nm: number;
            /**
             * Amplitude Variation
             * @default 0.08
             */
            amplitude_variation: number;
            /**
             * Seed
             * @default 42
             */
            seed: number;
        };
        /** MatchedReferenceLine */
        MatchedReferenceLine: {
            /** Element */
            element: string;
            /** Wavelength Nm */
            wavelength_nm: number;
            /** Relative Intensity */
            relative_intensity: number | null;
            /** Kind */
            kind: string;
            /** Observed Peak Nm */
            observed_peak_nm: number;
            /** Delta Nm */
            delta_nm: number;
        };
        /** ModelInfo */
        ModelInfo: {
            /** Model Id */
            model_id: string;
            /** Version */
            version: string | null;
            /** Model Type */
            model_type: string;
            /** Ready */
            ready: boolean;
            /** Score Kind */
            score_kind: string | null;
            /** Calibrated */
            calibrated: boolean;
            /** Data Source */
            data_source: string;
            /** Applicability */
            applicability: string;
        };
        /** PerElementMetrics */
        PerElementMetrics: {
            /** Support */
            support: number;
            /** Precision */
            precision: number | null;
            /** Recall */
            recall: number | null;
        };
        /** PredictArraysRequest */
        PredictArraysRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            input_type: "arrays";
            /** Wavelength Nm */
            wavelength_nm: number[];
            /** Intensity */
            intensity: number[];
            /**
             * Units
             * @constant
             */
            units: "nm";
            /**
             * Wavelength Medium
             * @constant
             */
            wavelength_medium: "vacuum";
            /**
             * Model Id
             * @default builtin-nnls
             */
            model_id: string;
        };
        /** PredictByIdRequest */
        PredictByIdRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            input_type: "spectrum_id";
            /** Spectrum Id */
            spectrum_id: string;
            /**
             * Model Id
             * @default builtin-nnls
             */
            model_id: string;
        };
        /** PredictionResponse */
        PredictionResponse: {
            /** Model Id */
            model_id: string;
            /** Model Version */
            model_version: string;
            /** Model Origin */
            model_origin: string;
            /** Reference Source */
            reference_source: string;
            /** Scores */
            scores: components["schemas"]["ElementScore"][];
            /** Score Kind */
            score_kind: string;
            /** Calibrated */
            calibrated: boolean;
            /** Thresholds */
            thresholds: {
                [key: string]: number;
            };
            /** Detected Elements */
            detected_elements: string[];
            /** Warnings */
            warnings: string[];
            /** Processing Time Ms */
            processing_time_ms: number;
            /** Matched Reference Lines */
            matched_reference_lines: components["schemas"]["MatchedReferenceLine"][];
        };
        /** SpectrumResponse */
        SpectrumResponse: {
            /** Spectrum Id */
            spectrum_id: string;
            /** Wavelength Nm */
            wavelength_nm: number[];
            /** Intensity */
            intensity: number[];
            /** Clean Signal */
            clean_signal?: number[] | null;
            /** True Labels */
            true_labels?: {
                [key: string]: number;
            } | null;
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** Base Sample Id */
            base_sample_id?: string | null;
            /** Reference Source */
            reference_source: string;
            /**
             * Origin
             * @enum {string}
             */
            origin: "generated" | "uploaded";
        };
        /** SubsetMetrics */
        SubsetMetrics: {
            /** Count */
            count: number;
            /** Micro F1 */
            micro_f1: number | null;
            /** Exact Match Accuracy */
            exact_match_accuracy: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Insufficient Storage */
            507: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    elements_api_v1_elements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElementsInfo"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Insufficient Storage */
            507: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfo"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Insufficient Storage */
            507: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    generate_api_v1_spectra_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateSpectrumRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpectrumResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Insufficient Storage */
            507: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_api_v1_spectra_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_v1_spectra_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpectrumResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Insufficient Storage */
            507: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_spectrum_api_v1_spectra__spectrum_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spectrum_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpectrumResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Insufficient Storage */
            507: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    predict_api_v1_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictByIdRequest"] | components["schemas"]["PredictArraysRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Insufficient Storage */
            507: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_experiments_api_v1_experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentSummary"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Insufficient Storage */
            507: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_experiment_api_v1_experiments__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentDetail"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Insufficient Storage */
            507: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
